name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run '...'
        2. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "1.0.0"
